import 'package:flutter_application_1/models/basic_model.dart';

List<Mobil> daftarMobil = [
  Mobil (
    gambar:"https://asset.honda-indonesia.com/variants/images/zueuXgccVJfz3uTrQlDSIFAHHiXLtUu9ny339ZXu.png",
    model:"Honda City",
    tipe:"1.5 Sedan CVT",
    warna:"Putih",
    kategori:"Sedan",
    tahunpembuatan:2026,
    harga:402000000,
  ),
  Mobil (
    gambar: "https://res.cloudinary.com/mufautoshow/image/upload/f_auto,f_auto/w_1200/v1751796556/moas/news/1751796554_honda-civic-rs-e-hev-sedan-hybrid-sporty-yang-efisien.png",
    model:"Honda Civic RS",
    tipe: "RS e:HEV (Hybrid)",
    warna: "Putih",
    kategori: "Sedan",
    tahunpembuatan: 2026,
    harga: 699000000,
  ),
  Mobil (
    gambar: "https://asset.honda-indonesia.com/variants/images/VY5QB4ASb892Uhq8I43lntdk96Mf3mOwrcENFE1j.png",
    model: "Honda StepWGN",
    tipe: "e:HEV (Hybrid)",
    warna: "Merah",
    kategori: "MPV / Minivan",
    tahunpembuatan: 2026,
    harga: 637800000,
  ),
  Mobil (
    gambar: "https://res.cloudinary.com/mufautoshow/image/upload/f_auto,f_auto/w_1200/v1694656071/moas/news/1694656048_all-new-crv-20l-rs-ehev-suv-premium-bermesin-hybrid.png",
    model: "Honda Prelude",
    tipe: "e:HEV (Hybrid)",
    warna: "Merah Maroon",
    kategori: "Sports & Coupe",
    tahunpembuatan: 2026,
    harga: 974900000,
  ),
  Mobil (
    gambar: "https://asset.honda-indonesia.com/variants/images/PQ5eDZbG4ve1ownP9pSZFJaJ9Fr5rXciXLd5uIu5.png",
    model: "Honda Civic Type R",
    tipe: "6-Speed M/T",
    warna: "Silver",
    kategori: "Sports & Coupe",
    tahunpembuatan: 2026,
    harga: 1446000000,
  ),
  Mobil (
    gambar: "https://asset.honda-indonesia.com/variants/images/jC3o3NEymOkMT7SgTmQoPlz5rYZdMQhLVWS0Ynrz.png",
    model: "Honda Brio",
    tipe: "Satya S M/T",
    warna: "Putih",
    kategori: "Hatchback & City Car",
    tahunpembuatan: 2026,
    harga: 170400000,
  ),
  Mobil (
    gambar:"https://asset.honda-indonesia.com/variants/images/mWtZtMRT42Cf6o4KdCBTDAtLyLDurQvqg8pkWC4g.png",
    model: "Honda Brio",
    tipe: "Satya S CVT",
    warna: "Putih",
    kategori: "Hatchback & City Car",
    tahunpembuatan: 2026,
    harga: 184500000,
  ),
  Mobil(
    gambar:"https://asset.honda-indonesia.com/variants/images/z3IlBtUoQMWNV5YTY13qjt1mt9D8uBUbmRrYVTI5.png",
    model: "Honda Brio",
    tipe: "Satya E M/T",
    warna: "Lime",
    kategori: "Hatchback & City Car",
    tahunpembuatan: 2026,
    harga: 185500000, 
    ),
  Mobil (
    gambar:"https://asset.honda-indonesia.com/variants/images/r0VotH5xqhyQ6jxjBO4pRJQWBVTR0iNrPbgL8x26.png",
    model: "Honda WR-V",
    tipe: "1.5L E CVT",
    warna: "Putih",
    kategori: "SUV & Crossover",
    tahunpembuatan: 2026,
    harga: 285100000,
    ),
  Mobil (
    gambar: "https://asset.honda-indonesia.com/variants/images/DkO4wfgxnHbEsTq3t7Fvpo8eX3nCXfOU79bzkmSf.png",
    model: "Honda WR-V",
    tipe: "1.5L RS",
    warna: "Coklat",
    kategori: "SUV & Crossover",
    tahunpembuatan: 2026,
    harga: 298600000,
  ),
  Mobil (
    gambar:"https://asset.honda-indonesia.com/variants/images/zoF7rGAmEsN9vaqlx3ZuUJTasbDtxVgILjKlTJY3.png",
    model: "Honda WR-V",
    tipe: "1.5L RS with Honda Sensing",
    warna: "Merah Maroon",
    kategori: "SUV & Crossover",
    tahunpembuatan: 2026,
    harga: 322100000,
  )
];
